# Configuration for connection finance_s3_msft
definition_type: connection
resource_name: "finance_s3_msft"
source_configuration_path: sources/finance_msft_source/configuration.yaml
destination_configuration_path: destinations/s3_msft_destination/configuration.yaml

# EDIT THE CONFIGURATION BELOW!
configuration:
  status: active # REQUIRED | string | Allowed values: active, inactive, deprecated
  skip_reset: false # OPTIONAL | boolean | Flag to check if the connection should be reset after a connection update
  namespace_definition: source # OPTIONAL | string | Allowed values: source, destination, customformat
  namespace_format: "${SOURCE_NAMESPACE}" # OPTIONAL | string | Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If "${SOURCE_NAMESPACE}" then behaves like namespaceDefinition = 'source'.
  prefix: "" # REQUIRED | Prefix that will be prepended to the name of each stream when it is written to the destination
  resource_requirements: # OPTIONAL | object | Resource requirements to run workers (blank for unbounded allocations)
    cpu_limit: "" # OPTIONAL
    cpu_request: "" # OPTIONAL
    memory_limit: "" # OPTIONAL
    memory_request: "" # OPTIONAL
  schedule_type: manual # OPTIONAL | string | Allowed values: basic, cron, manual
  #schedule_data: # OPTIONAL | object
  #  basic_schedule:
  #    time_unit: hours # REQUIRED | string | Allowed values: minutes, hours, days, weeks, months
  #    units: 1 # REQUIRED | integer
    # cron:
    #   cron_time_zone: "UTC" # REQUIRED | string
    #   cron_expression: "* */2 * * * ?" # REQUIRED | string
  sync_catalog: # OPTIONAL | object | 🚨 ONLY edit streams.config, streams.stream should not be edited as schema cannot be changed.
    streams:
      - config:
          alias_name: time_series_intraday
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key: []
          selected: false
          suggested: false
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              1. open:
                type:
                  - string
                  - 'null'
              2. high:
                type:
                  - string
                  - 'null'
              3. low:
                type:
                  - string
                  - 'null'
              4. close:
                type:
                  - string
                  - 'null'
              5. volume:
                type:
                  - string
                  - 'null'
            type: object
          name: time_series_intraday
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh
      - config:
          alias_name: time_series_daily
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key: []
          selected: true
          suggested: false
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              1. open:
                type:
                  - string
                  - 'null'
              2. high:
                type:
                  - string
                  - 'null'
              3. low:
                type:
                  - string
                  - 'null'
              4. close:
                type:
                  - string
                  - 'null'
              5. volume:
                type:
                  - string
                  - 'null'
            type: object
          name: time_series_daily
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh
      - config:
          alias_name: time_series_daily_adjusted
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key: []
          selected: false
          suggested: false
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              1. open:
                type: string
              2. high:
                type: string
              3. low:
                type: string
              4. close:
                type: string
              5. adjusted close:
                type: string
              6. volume:
                type: string
              7. dividend amount:
                type: string
              8. split coefficient:
                type: string
            type: object
          name: time_series_daily_adjusted
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh
      - config:
          alias_name: time_series_weekly
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key: []
          selected: false
          suggested: false
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              1. open:
                type:
                  - string
                  - 'null'
              2. high:
                type:
                  - string
                  - 'null'
              3. low:
                type:
                  - string
                  - 'null'
              4. close:
                type:
                  - string
                  - 'null'
              5. volume:
                type:
                  - string
                  - 'null'
            type: object
          name: time_series_weekly
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh
      - config:
          alias_name: time_series_weekly_adjusted
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key: []
          selected: false
          suggested: false
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              1. open:
                type: string
              2. high:
                type: string
              3. low:
                type: string
              4. close:
                type: string
              5. adjusted close:
                type: string
              6. volume:
                type: string
              7. dividend amount:
                type: string
            type: object
          name: time_series_weekly_adjusted
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh
      - config:
          alias_name: time_series_monthly
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key: []
          selected: false
          suggested: false
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              1. open:
                type:
                  - string
                  - 'null'
              2. high:
                type:
                  - string
                  - 'null'
              3. low:
                type:
                  - string
                  - 'null'
              4. close:
                type:
                  - string
                  - 'null'
              5. volume:
                type:
                  - string
                  - 'null'
            type: object
          name: time_series_monthly
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh
      - config:
          alias_name: time_series_monthly_adjusted
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key: []
          selected: false
          suggested: false
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              1. open:
                type: string
              2. high:
                type: string
              3. low:
                type: string
              4. close:
                type: string
              5. adjusted close:
                type: string
              6. volume:
                type: string
              7. dividend amount:
                type: string
            type: object
          name: time_series_monthly_adjusted
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh
      - config:
          alias_name: quote
          cursor_field: []
          destination_sync_mode: overwrite
          primary_key: []
          selected: false
          suggested: false
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              Global Quote:
                01. symbol:
                  type:
                    - string
                    - 'null'
                02. open:
                  type:
                    - string
                    - 'null'
                03. high:
                  type:
                    - string
                    - 'null'
                04. low:
                  type:
                    - string
                    - 'null'
                05. price:
                  type:
                    - string
                    - 'null'
                06. volume:
                  type:
                    - string
                    - 'null'
                07. latest trading day:
                  type:
                    - string
                    - 'null'
                08. previous close:
                  type:
                    - string
                    - 'null'
                09. change:
                  type:
                    - string
                    - 'null'
                10. change percent:
                  type:
                    - string
                    - 'null'
            type: object
          name: quote
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh